### ISSUE TITLE
Extra, super basic info

### ISSUE THREAD

**Issue by AntonOfTheWoods** [sfreytag/laravel-vite-pwa#1]
I have had quite a few difficulties getting things to work, particularly given I just wanted a bare service worker for `fetch` management (at this stage anyway...).

```
    VitePWA({
      outDir: "public/build",
      srcDir: "resources/js/lib",  // this will probably be different
      filename: "service-worker.ts",  // this will probably be different
      strategies: "injectManifest",
      injectRegister: false,
      manifest: false,
      injectManifest: {
        injectionPoint: undefined,
      },
      devOptions: {
        enabled: true,
        type: "module",
      },
    }),
```

I was also having difficulties with web workers and had to do a manual hack via a reverse proxy (an external service pointing to `host.k3d.internal`) for development to work (I'm using `k3d` to host multiple services), namely the stuff mentioned [here](https://github.com/laravel/vite-plugin/issues/106).

I'm not sure whether you intended to have a basic setup documented here also but the above works, at least with the addition of forcing the `/dev-js?dev-js` also to the frontend via the reverse proxy.

I can keep updating here if I find any extra gotchas if you are interested.

**Comment by sfreytag** [comment]
Thanks for the contribution... I'm not really sure yet what this repo will become, but it did seem that it was getting too complex to keep track of everyone's thoughts in that issue thread. One possibility is that the vite.config.ts could be split into various versions for people to pick from - current repo is the full-blown PWA, and then could add yours as bare-bones for a SW just for fetch, etc.

**Comment by sfreytag** [comment]
...and yes please for any extra gotchas you find!
